name: Build and Release Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'
          cache: true

      - name: Disable Flutter Analytics
        run: flutter config --no-analytics

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Release APK
        run: flutter build apk --release

      - name: Get Current Date
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Create Release with GitHub CLI
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME="v${{ steps.date.outputs.date }}"
          RELEASE_NAME="Release ${{ steps.date.outputs.date }}"
          
          # Create release
          gh release create "$TAG_NAME" \
            --title "$RELEASE_NAME" \
            --notes "Automated release for ${{ steps.date.outputs.date }}" \
            build/app/outputs/flutter-apk/app-release.apk
